## Weather and climate: AgERA5{.unnumbered}

This dataset provides daily surface meteorological data for the period from 1979 to present as input for agriculture and agro-ecological studies. This dataset is based on the hourly ECMWF ERA5 data at surface level and is referred to as AgERA5. Acquisition and pre-processing of the original ERA5 data is a complex and specialized job


### Dataset characteristics {.unlisted .unnumbered}
-   Spatial resolution: 0.1 x 0.1 degree
-   Spatial coverage: 90ºN to 90ºS
-   Temporal resolution: daily
-   Temporal coverage:1979-present
-   Update frequency / latency: 8 days
-   Version: 1.0
-   License: Copernicus license
-   Official website: <https://cds.climate.copernicus.eu/cdsapp#!/dataset/sis-agrometeorological-indicators?tab=overview>


### Variables included {.unlisted .unnumbered}

| Variable name | Description                                              | Temporal resolution | Units  |
|---------------|-----------------------------|---------------|---------------|
| 10m wind speed | Mean wind speed at a height of 10 metres above the surface over the period 00h-24h local time | daily | m/s
| Max. temperature | Air temperature at a height of 2 metres above the surface. Maximum of 00-24h period local time. | daily | K
| Mean temperature | Air temperature at a height of 2 metres above the surface. Average of 00-24h period local time. | daily | K
| Min. temperature | Air temperature at a height of 2 metres above the surface. Minimum of 00-24h period local time. | daily | K
| Precipitation | Total volume of liquid water (cubic mm) precipitated over the period 00h-24h local time per unit of area (mm sq.), per day. | daily | mm/day
| Relative humidity | Relative humidity at 06h, 09h, 12h. 15h, 18h (local time) at a height of 2 metres above the surface. This variable describes the amount of water vapour present in air expressed as a percentage of the amount needed for saturation at the same temperature. | daily | %
| Solar radiation | Total amount of energy provided by solar radiation at the surface over the period 00-24h local time per unit area and time. | daily | J/m2/day




